### ISSUE TITLE
Nodes in goal over the area

### ISSUE THREAD

**Issue by fish-404** [pcottle/learnGitBranching#1003]
When I use my personal notebook to visit this site, I find the top node will over the area. When I use my work computer which has bigger display, I won't meet this problem. Inspect in my notebook, find the dynamic `top` value is a negative. My notebook size is 15.6 in. 

If I use this custom style to force the top unset, everyting is ok. 

``` css
div.canvasTerminalHolder>div.terminal-window-holder div.inside svg {
    top: unset !important;
}
```

![screenshot](https://user-images.githubusercontent.com/29678177/187019517-cfd4c8cc-30dc-4a63-9594-84574d2e305d.png)
