### ISSUE TITLE
Better position of console and goal windows

### ISSUE THREAD

**Issue by KedamaMouse** [pcottle/learnGitBranching#987]
Having the goal window overlap with the console by default is bad design, because it hides the output of any commands.
The console doesn't really need to be that tall, so I think an obvious solution would be to have the console and goal each take up half the height of the screen.
Sure you can hide the goal window, but folks generally wouldn't have to with just a bit better use of space.

**Comment by danny-lin714** [comment]
Can't agree with you more! The goal window disturbs me to learn git. 
But btw this project helps me a lot. It's awesome!

**Comment by fish-404** [comment]
I use custom styles to change the goal window default shown on the right side. 
``` css
@-moz-document domain("learngitbranching.js.org") {
    div.canvasTerminalHolder {
        right: 0;
        left: unset;
    }
    
    div.canvasTerminalHolder>div.terminal-window-holder {
        left: unset !important;
    }
}
```
